import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { ExternalLink, Pencil, Printer, Trash2 } from "lucide-react";
import { Guard } from "@/components/Guard";
import { Button } from "@/items/Button";
import { FilterBar } from "@/items/FilterBar";
import { FieldRenderer } from "@/engine/FieldRenderer";
import { EntityRelationDetail } from "@/engine/EntityRelationDetail";
import { EntitySignatureModal } from "@/items/EntitySignatureModal";
import { Modal } from "@/items/Modal";
import { Offpanel } from "@/items/Offpanel";
import { ScreenHeader } from "@/items/ScreenHeader";
import { Table, type Column } from "@/items/Table";
import { TableImageCell } from "@/items/TableImageCell";
import { formatCellValue } from "@/engine/screenUtils";
import {
  issuesByField,
  parseEmbedListValue,
  parseValidationReportFromError,
  validateScreenForm,
} from "@/engine/validation";
import { ValidationBanner } from "@/items/ValidationBanner";
import type { Privilege } from "@/types/auth";
import { PrintListPdfModal } from "@/items/PrintListPdfModal";
import { EntityCsvImportModal } from "@/items/EntityCsvImportModal";
import { printEntityRowPdf } from "@/lib/print/rowPrint";
import { exportEntityCsv } from "@/lib/entityCsv";
import { useAlert } from "@/contexts/AlertContext";
import type { ReactNode } from "react";
import { BUSINESS_SESSION_CHANGED_EVENT, ENTITY_CSV_IMPORT_OPEN_EVENT } from "@/constants/events";
import type { ScreenConfigFile, ScreenRow, ValidationIssue } from "@/types/screen";

interface DataScreenProps {
  config: ScreenConfigFile;
  /** Préremplit le modal de création puis l’ouvre une fois (ex. demande Loggy). */
  initialCreateValues?: ScreenRow;
  onInitialCreateApplied?: () => void;
  /** Actions supplémentaires par ligne (ex. déstockage). */
  extraRowActions?: (row: ScreenRow, reload: () => void) => ReactNode;
}

type FormMode = "create" | "edit" | "detail" | null;

export function DataScreen({
  config,
  initialCreateValues,
  onInitialCreateApplied,
  extraRowActions,
}: DataScreenProps) {
  const screenKey = config.screen.key;
  const pk = config.screen.primaryKey;

  const hasRelations = useMemo(
    () =>
      config.fields.some(
        (f) =>
          f.type === "entity_ref" ||
          f.type === "entity_embed" ||
          f.type === "entity_embed_list",
      ),
    [config.fields],
  );

  const [rows, setRows] = useState<ScreenRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState<Record<string, string>>({});
  const [formMode, setFormMode] = useState<FormMode>(null);
  const [formValues, setFormValues] = useState<ScreenRow>({});
  const [relationDetailId, setRelationDetailId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [formValidation, setFormValidation] = useState<{
    errors: ValidationIssue[];
    warnings: ValidationIssue[];
  }>({ errors: [], warnings: [] });
  const [filterValidation, setFilterValidation] = useState<{
    errors: ValidationIssue[];
    warnings: ValidationIssue[];
  }>({ errors: [], warnings: [] });
  const uploadDraftIdRef = useRef(crypto.randomUUID());
  const initialCreateAppliedRef = useRef(false);
  const [entitySignatureTarget, setEntitySignatureTarget] = useState<{
    entityKey: string;
    recordId: string;
  } | null>(null);
  const { showSuccess, showError, showInfo } = useAlert();

  const isAutoSignatureTask = useCallback(
    (row: ScreenRow) => {
      if (screenKey !== "tache") return false;
      const type = String(row.type_tache ?? "");
      const entityKey = String(row.entite_a_signer ?? row.entite_a_valider ?? "").trim();
      const recordId = String(row.enregistrement_id ?? "").trim();
      return (
        (type === "signature" || type === "validation") &&
        entityKey !== "" &&
        recordId !== ""
      );
    },
    [screenKey],
  );

  const openEntitySignatureFromTask = useCallback((row: ScreenRow) => {
    const entityKey = String(row.entite_a_signer ?? row.entite_a_valider ?? "").trim();
    const recordId = String(row.enregistrement_id ?? "").trim();
    if (!entityKey || !recordId) return;
    setEntitySignatureTarget({ entityKey, recordId });
  }, []);

  const filterFields = useMemo(
    () => config.fields.filter((f) => f.filter?.enabled),
    [config.fields],
  );

  const listFields = useMemo(
    () => config.fields.filter((f) => f.list?.enabled && f.type !== "hidden"),
    [config.fields],
  );

  const formFieldsForMode = useCallback(
    (mode: FormMode) =>
      config.fields.filter((f) => {
        if (f.type === "hidden" || f.type === "detail_link") return false;
        if (
          mode === "create" &&
          (f.key === "created_at" ||
            (f.form?.readOnly && !f.form?.autoGenerated))
        ) {
          return false;
        }
        return true;
      }),
    [config.fields],
  );

  const formFields = useMemo(
    () => formFieldsForMode(formMode),
    [formFieldsForMode, formMode],
  );

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await invoke<ScreenRow[]>("dda_list", {
        payload: { screen_key: screenKey, filters },
      });
      setRows(data);
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  }, [screenKey, filters]);

  useEffect(() => {
    void load();
  }, [load]);

  useEffect(() => {
    const onSession = () => void load();
    window.addEventListener(BUSINESS_SESSION_CHANGED_EVENT, onSession);
    return () => window.removeEventListener(BUSINESS_SESSION_CHANGED_EVENT, onSession);
  }, [load]);

  useEffect(() => {
    const onImportOpen = (e: Event) => {
      const key = (e as CustomEvent<{ entityKey?: string }>).detail?.entityKey;
      if (key && key !== screenKey) return;
      setCsvImportOpen(true);
      showInfo(`Import CSV pour « ${config.screen.label} » — déposez votre fichier ci-dessous.`);
    };
    window.addEventListener(ENTITY_CSV_IMPORT_OPEN_EVENT, onImportOpen);
    return () => window.removeEventListener(ENTITY_CSV_IMPORT_OPEN_EVENT, onImportOpen);
  }, [screenKey, config.screen.label, showInfo]);

  const openRelationDetail = (row: ScreenRow) => {
    const id = String(row[pk] ?? "");
    if (id) setRelationDetailId(id);
  };

  const columns: Column<ScreenRow>[] = useMemo(
    () =>
      listFields.map((f) => ({
        key: f.key,
        header: f.label,
        sortable: f.list?.sortable,
        render: (row) => {
          if (f.type === "detail_link") {
            return (
              <Button
                size="sm"
                variant="secondary"
                onClick={(e) => {
                  e.stopPropagation();
                  openRelationDetail(row);
                }}
              >
                <ExternalLink className="h-3.5 w-3.5" />
                Détail
              </Button>
            );
          }
          const raw = row[f.key] ?? row[f.column];
          if (f.type === "image") {
            const path = raw != null ? String(raw) : "";
            return <TableImageCell relativePath={path || undefined} />;
          }
          if (f.type === "entity_ref") {
            return raw != null && String(raw).trim() ? String(raw) : "—";
          }
          if (f.type === "entity_embed_list") {
            const rows = parseEmbedListValue(raw);
            return rows.length > 0 ? `${rows.length} élément(s)` : "—";
          }
          return formatCellValue(f, raw);
        },
      })),
    [listFields, pk],
  );

  const runFormValidation = (values: ScreenRow) => {
    const report = validateScreenForm(config, values);
    setFormValidation({ errors: report.errors, warnings: report.warnings });
    return report;
  };

  const runFilterValidation = (filterValues: Record<string, string>) => {
    const report = validateScreenForm(config, filterValues, { filtersOnly: true });
    setFilterValidation({ errors: report.errors, warnings: report.warnings });
    return report;
  };

  const defaultTimeValue = (): string => {
    const now = new Date();
    return `${String(now.getHours()).padStart(2, "0")}:${String(now.getMinutes()).padStart(2, "0")}`;
  };

  const openCreateWith = useCallback(
    (prefill?: ScreenRow) => {
      const fields = formFieldsForMode("create");
      const initial: ScreenRow = {};
      for (const f of fields) {
        if (f.default != null && f.default !== "") {
          initial[f.key] = f.default;
        } else if (f.type === "time" && f.required) {
          initial[f.key] = defaultTimeValue();
        }
      }
      if (prefill) {
        for (const [key, value] of Object.entries(prefill)) {
          if (value !== null && value !== undefined && value !== "") {
            initial[key] = value;
          }
        }
      }
      setFormValues(initial);
      setFormValidation({ errors: [], warnings: [] });
      setFormMode("create");
    },
    [formFieldsForMode],
  );

  const openCreate = () => {
    openCreateWith();
  };

  useEffect(() => {
    initialCreateAppliedRef.current = false;
  }, [screenKey]);

  useEffect(() => {
    if (!initialCreateValues || initialCreateAppliedRef.current) return;
    initialCreateAppliedRef.current = true;
    openCreateWith(initialCreateValues);
    onInitialCreateApplied?.();
  }, [initialCreateValues, openCreateWith, onInitialCreateApplied]);

  const openRow = (row: ScreenRow, mode: "edit" | "detail") => {
    if (isAutoSignatureTask(row)) {
      openEntitySignatureFromTask(row);
      return;
    }
    if (mode === "detail" && hasRelations) {
      openRelationDetail(row);
      return;
    }
    setFormValues({ ...row });
    setFormValidation({ errors: [], warnings: [] });
    setFormMode(mode);
  };

  const closeForm = () => {
    setFormMode(null);
    setFormValues({});
    setFormValidation({ errors: [], warnings: [] });
  };

  const setField = (key: string, value: unknown) => {
    setFormValues((prev) => {
      const next = { ...prev, [key]: value };
      runFormValidation(next);
      return next;
    });
  };

  const submitForm = async () => {
    setError(null);
    const report = runFormValidation(formValues);
    if (!report.valid) return;
    try {
      if (formMode === "create") {
        await invoke("dda_create", {
          payload: { screen_key: screenKey, data: formValues },
        });
      } else if (formMode === "edit") {
        const id = String(formValues[pk] ?? "");
        await invoke("dda_update", {
          payload: { screen_key: screenKey, id, data: formValues },
        });
      }
      closeForm();
      showSuccess(
        formMode === "create"
          ? "Enregistrement créé avec succès."
          : "Enregistrement mis à jour.",
      );
      await load();
    } catch (e) {
      const parsed = parseValidationReportFromError(e);
      if (parsed) {
        setFormValidation({ errors: parsed.errors, warnings: parsed.warnings });
      } else {
        const msg = String(e);
        setError(msg);
        showError(msg);
      }
    }
  };

  const [printingId, setPrintingId] = useState<string | null>(null);
  const [printListOpen, setPrintListOpen] = useState(false);
  const [csvImportOpen, setCsvImportOpen] = useState(false);

  const printRow = async (row: ScreenRow) => {
    const id = String(row[pk] ?? "");
    if (!id) return;
    setPrintingId(id);
    setError(null);
    try {
      await printEntityRowPdf(screenKey, id);
      showSuccess("PDF généré et téléchargé.");
    } catch (e) {
      const msg = String(e);
      setError(msg);
      showError(`Échec de la génération PDF : ${msg}`);
    } finally {
      setPrintingId(null);
    }
  };

  const rowActions = (row: ScreenRow) => (
    <div className="flex gap-1 justify-end">
      {extraRowActions?.(row, () => void load())}
      {hasRelations && (
        <Guard privilege={config.screen.privileges.view}>
          <Button
            variant="ghost"
            size="sm"
            aria-label="Détail relations"
            title="Voir les liaisons embarquées"
            onClick={(e) => {
              e.stopPropagation();
              openRelationDetail(row);
            }}
          >
            <ExternalLink className="h-4 w-4" />
          </Button>
        </Guard>
      )}
      <Guard privilege={config.screen.privileges.view}>
        <Button
          variant="ghost"
          size="sm"
          aria-label="Imprimer PDF"
          title="Imprimer la fiche PDF"
          disabled={printingId === String(row[pk] ?? "")}
          onClick={(e) => {
            e.stopPropagation();
            void printRow(row);
          }}
        >
          <Printer className={`h-4 w-4 ${printingId === String(row[pk] ?? "") ? "animate-pulse" : ""}`} />
        </Button>
      </Guard>
      <Guard privilege={config.screen.privileges.update as Privilege}>
        {!isAutoSignatureTask(row) && (
          <Button
            variant="ghost"
            size="sm"
            aria-label="Modifier"
            onClick={(e) => {
              e.stopPropagation();
              openRow(row, "edit");
            }}
          >
            <Pencil className="h-4 w-4" />
          </Button>
        )}
      </Guard>
      <Guard privilege={config.screen.privileges.delete as Privilege}>
        <Button
          variant="ghost"
          size="sm"
          aria-label="Supprimer"
          onClick={(e) => {
            e.stopPropagation();
            void deleteRow(row);
          }}
        >
          <Trash2 className="h-4 w-4 text-primary" />
        </Button>
      </Guard>
    </div>
  );

  const deleteRow = async (row: ScreenRow) => {
    const id = String(row[pk] ?? "");
    if (!id || !window.confirm("Supprimer cet enregistrement ?")) return;
    try {
      await invoke("dda_delete", { payload: { screen_key: screenKey, id } });
      await load();
    } catch (e) {
      setError(String(e));
    }
  };

  const createLayout = config.layout.forms?.create;
  const editLayout = config.layout.forms?.edit;
  const detailLayout = config.layout.forms?.detail;
  const activeLayout =
    formMode === "create" ? createLayout : formMode === "edit" ? editLayout : detailLayout;
  const formReadOnly =
    (formMode === "detail" && (detailLayout?.readOnly ?? true)) ||
    (formMode === "edit" && isAutoSignatureTask(formValues));
  const excludeRecordId =
    formMode === "edit" && formValues[pk] != null ? String(formValues[pk]) : undefined;

  const formErrorsMap = issuesByField(formValidation.errors);
  const formWarningsMap = issuesByField(formValidation.warnings);
  const filterErrorsMap = issuesByField(filterValidation.errors);
  const filterWarningsMap = issuesByField(filterValidation.warnings);

  const formBody = (
    <div className="space-y-4">
      <ValidationBanner errors={formValidation.errors} warnings={formValidation.warnings} />
      {error && (
        <p className="text-sm text-primary" role="alert">
          {error}
        </p>
      )}
      {formFields.map((field) => (
        <FieldRenderer
          key={field.key}
          field={field}
          allFields={config.fields}
          fieldErrorsMap={formErrorsMap}
          fieldWarningsMap={formWarningsMap}
          values={formValues}
          onChange={setField}
          onBatchChange={(updates) => {
            setFormValues((prev) => {
              const next = { ...prev, ...updates };
              runFormValidation(next);
              return next;
            });
          }}
          onBlur={() => runFormValidation(formValues)}
          readOnly={formReadOnly}
          fieldError={formErrorsMap[field.key]}
          fieldWarning={formWarningsMap[field.key]}
          screenKey={screenKey}
          uploadDraftId={uploadDraftIdRef.current}
          storageFolders={config.screen.storage?.folders}
          excludeRecordId={excludeRecordId}
        />
      ))}
    </div>
  );

  return (
    <div className="p-8">
      <ScreenHeader
        layout={config.layout.list}
        privileges={config.screen.privileges}
        onCreate={openCreate}
        onRefresh={() => void load()}
        onPrintListPdf={() => setPrintListOpen(true)}
        onImportCsv={() => setCsvImportOpen(true)}
        onExportCsv={() => void exportEntityCsv(screenKey, config.screen.label)}
        loading={loading}
      />

      <PrintListPdfModal
        open={printListOpen}
        onClose={() => setPrintListOpen(false)}
        config={config}
      />
      <EntityCsvImportModal
        entityKey={screenKey}
        entityLabel={config.screen.label}
        open={csvImportOpen}
        onClose={() => setCsvImportOpen(false)}
        onImported={() => void load()}
      />

      <div className="mb-6 space-y-3">
        <FilterBar
          fields={filterFields}
          values={filters}
          fieldErrors={filterErrorsMap}
          fieldWarnings={filterWarningsMap}
          onChange={(key, value) => {
            const next = { ...filters, [key]: value };
            setFilters(next);
            runFilterValidation(next);
          }}
        />
        {(filterValidation.errors.length > 0 || filterValidation.warnings.length > 0) && (
          <ValidationBanner
            errors={filterValidation.errors}
            warnings={filterValidation.warnings}
          />
        )}
      </div>

      {error && !formMode && (
        <p className="text-sm text-primary mb-4" role="alert">
          {error}
        </p>
      )}

      <Table
        pageSize={config.layout.list.pagination?.pageSize}
        pageSizeOptions={config.layout.list.pagination?.pageSizeOptions}
        showPageSizeSelector={config.layout.list.pagination?.showPageSizeSelector}
        hideWhenSinglePage={config.layout.list.pagination?.hideWhenSinglePage}
        columns={[
          ...columns,
          {
            key: "_actions",
            header: "",
            className: "w-36",
            render: (row: ScreenRow) => rowActions(row),
          } as Column<ScreenRow>,
        ]}
        data={rows}
        keyExtractor={(row) => String(row[pk] ?? "")}
        emptyMessage={loading ? "Chargement…" : "Aucun enregistrement"}
        onRowClick={(row) => {
          if (config.layout.list.rowClick === "detail") {
            openRow(row, "detail");
          } else if (config.layout.list.rowClick === "edit") {
            openRow(row, "edit");
          }
        }}
      />

      {createLayout?.mode === "modal" && (
        <Modal
          open={formMode === "create"}
          onClose={closeForm}
          title={createLayout.title}
          size="lg"
          footer={
            <div className="flex justify-end gap-2">
              <Button variant="ghost" onClick={closeForm}>
                Annuler
              </Button>
              <Button onClick={() => void submitForm()}>
                {createLayout.submitLabel ?? "Enregistrer"}
              </Button>
            </div>
          }
        >
          {formBody}
        </Modal>
      )}

      {editLayout?.mode === "modal" && (
        <Modal
          open={formMode === "edit"}
          onClose={closeForm}
          title={editLayout.title}
          size="lg"
          footer={
            !isAutoSignatureTask(formValues) ? (
              <div className="flex justify-end gap-2">
                <Button variant="ghost" onClick={closeForm}>
                  Annuler
                </Button>
                <Button onClick={() => void submitForm()}>
                  {editLayout.submitLabel ?? "Enregistrer"}
                </Button>
              </div>
            ) : (
              <div className="flex justify-end">
                <Button variant="ghost" onClick={closeForm}>
                  Fermer
                </Button>
              </div>
            )
          }
        >
          {formBody}
        </Modal>
      )}

      {detailLayout?.mode === "modal" && formMode === "detail" && !hasRelations && (
        <Modal
          open
          onClose={closeForm}
          title={detailLayout.title}
          size="lg"
          footer={
            <Button variant="ghost" onClick={closeForm}>
              Fermer
            </Button>
          }
        >
          {formBody}
        </Modal>
      )}

      {activeLayout?.mode === "offpanel" && formMode && formMode !== "create" && (
        <Offpanel
          open
          onClose={closeForm}
          title={activeLayout.title}
          width="lg"
          headerActions={
            !formReadOnly ? (
              <Button size="sm" onClick={() => void submitForm()}>
                {activeLayout.submitLabel ?? "Enregistrer"}
              </Button>
            ) : (
              <Button size="sm" variant="ghost" onClick={closeForm}>
                Fermer
              </Button>
            )
          }
        >
          {formBody}
        </Offpanel>
      )}

      {relationDetailId && (
        <EntityRelationDetail
          screenKey={screenKey}
          recordId={relationDetailId}
          open={Boolean(relationDetailId)}
          onClose={() => setRelationDetailId(null)}
          title={detailLayout?.title ?? `Fiche — ${config.screen.label}`}
        />
      )}

      {entitySignatureTarget && (
        <EntitySignatureModal
          entityKey={entitySignatureTarget.entityKey}
          recordId={entitySignatureTarget.recordId}
          open
          onClose={() => setEntitySignatureTarget(null)}
          onSigned={() => {
            setEntitySignatureTarget(null);
            void load();
          }}
        />
      )}
    </div>
  );
}
