export interface ScreenConfigFile {
  screen: ScreenMeta;
  layout: ScreenLayout;
  fields: FieldDef[];
}

export interface ScreenMeta {
  key: string;
  label: string;
  labelPlural?: string;
  icon?: string;
  route: string;
  system?: boolean;
  aiEditable?: boolean;
  table: string;
  primaryKey: string;
  labelField: string;
  defaultOrderBy?: string;
  privileges: ScreenPrivileges;
  print?: PrintMeta;
  storage?: StorageMeta;
}

export interface ScreenPrivileges {
  view: string;
  create: string;
  update: string;
  delete: string;
  import?: string;
  export?: string;
}

export interface PrintMeta {
  enabled?: boolean;
  screenKey: string;
  singleObject?: boolean;
  templateName?: string;
}

export interface StorageMeta {
  folders: string[];
}

export interface ScreenLayout {
  list: ListLayout;
  forms?: FormsLayout;
}

export interface ListPaginationConfig {
  pageSize?: number;
  pageSizeOptions?: number[];
  showPageSizeSelector?: boolean;
  hideWhenSinglePage?: boolean;
}

export interface ListLayout {
  title: string;
  subtitle?: string;
  actions?: string[];
  rowClick?: string;
  pagination?: ListPaginationConfig;
}

export interface FormsLayout {
  create?: FormLayout;
  edit?: FormLayout;
  detail?: FormLayout;
}

export interface FormLayout {
  title: string;
  mode: "modal" | "offpanel";
  submitLabel?: string;
  readOnly?: boolean;
}

export type FieldType =
  | "text"
  | "number"
  | "stock"
  | "compteur"
  | "matricule"
  | "select"
  | "hidden"
  | "date"
  | "time"
  | "datetime"
  | "boolean"
  | "image"
  | "images"
  | "entity_ref"
  | "entity_ref_list"
  | "entity_embed"
  | "entity_embed_list"
  | "detail_link";

export interface FieldValidation {
  required?: boolean;
  requiredMessage?: string;
  minLength?: number;
  maxLength?: number;
  minLengthMessage?: string;
  maxLengthMessage?: string;
  min?: number;
  max?: number;
  minMessage?: string;
  maxMessage?: string;
  pattern?: string;
  patternMessage?: string;
  oneOf?: string[];
  oneOfMessage?: string;
  fixHint?: string;
  warnings?: FieldWarningRule[];
}

export interface FieldWarningRule {
  when: { field: string; equals: string | number | boolean };
  message: string;
  fixHint?: string;
}

export interface FieldDef {
  key: string;
  column: string;
  type: FieldType;
  label: string;
  required?: boolean;
  default?: string | number | boolean;
  options?: FieldOption[];
  list?: { enabled?: boolean; sortable?: boolean };
  filter?: { enabled?: boolean; operator?: string };
  form?: {
    colSpan?: number;
    placeholder?: string;
    min?: number;
    step?: number;
    readOnly?: boolean;
    /** Affiché à la création malgré readOnly (compteur auto). */
    autoGenerated?: boolean;
    storageFolder?: string;
    maxFiles?: number;
    accept?: string;
    refEntity?: string;
    relationExclusiveParent?: boolean;
    relationMultiple?: boolean;
    /** Champ dupliqué depuis une entité fille embarquée. */
    embedParent?: string;
  };
  visibleWhen?: { field: string; equals: string | number | boolean };
  validation?: FieldValidation;
}

export interface FieldOption {
  value: string;
  label: string;
}

export type ScreenRow = Record<string, unknown>;

export interface ValidationIssue {
  field: string;
  label: string;
  level: "error" | "warning";
  code: string;
  message: string;
  fixHint?: string;
}

export interface ValidationReport {
  valid: boolean;
  errors: ValidationIssue[];
  warnings: ValidationIssue[];
}
